const languages = {
  en: {
    name: 'English',
    stopWords: ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'aren\'t', 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can\'t', 'cannot', 'could', 'couldn\'t', 'did', 'didn\'t', 'do', 'does', 'doesn\'t', 'doing', 'don\'t', 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn\'t', 'has', 'hasn\'t', 'have', 'haven\'t', 'having', 'he', 'he\'d', 'he\'ll', 'he\'s', 'her', 'here', 'here\'s', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'how\'s', 'i', 'i\'d', 'i\'ll', 'i\'m', 'i\'ve', 'if', 'in', 'into', 'is', 'isn\'t', 'it', 'it\'s', 'its', 'itself', 'let\'s', 'me', 'more', 'most', 'mustn\'t', 'my', 'myself', 'no', 'nor', 'not', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought', 'our', 'ours ourselves', 'out', 'over', 'own', 'same', 'shan\'t', 'she', 'she\'d', 'she\'ll', 'she\'s', 'should', 'shouldn\'t', 'so', 'some', 'such', 'than', 'that', 'that\'s', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'there\'s', 'these', 'they', 'they\'d', 'they\'ll', 'they\'re', 'they\'ve', 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was', 'wasn\'t', 'we', 'we\'d', 'we\'ll', 'we\'re', 'we\'ve', 'were', 'weren\'t', 'what', 'what\'s', 'when', 'when\'s', 'where', 'where\'s', 'which', 'while', 'who', 'who\'s', 'whom', 'why', 'why\'s', 'with', 'won\'t', 'would', 'wouldn\'t', 'you', 'you\'d', 'you\'ll', 'you\'re', 'you\'ve', 'your', 'yours', 'yourself', 'yourselves'],
  },
  pt: {
    name: 'Portuguese',
    stopWords: ['a', 'ah', 'ai', 'algo', 'algum', 'alguma', 'algumas', 'alguns', 'alguém', 'alô', 'ambos', 'ante', 'ao', 'aos', 'apenas', 'após', 'aquela', 'aquelas', 'aquele', 'aqueles', 'aquilo', 'as', 'até', 'bis', 'cada', 'certa', 'certas', 'certo', 'certos', 'chi', 'com', 'comigo', 'conforme', 'conosco', 'consigo', 'contigo', 'contra', 'convosco', 'cuja', 'cujas', 'cujo', 'cujos', 'da', 'daquela', 'daquelas', 'daquele', 'daqueles', 'daquilo', 'das', 'de', 'dela', 'delas', 'dele', 'deles', 'desde', 'dessa', 'dessas', 'desse', 'desses', 'desta', 'destas', 'deste', 'destes', 'disso', 'disto', 'do', 'dos', 'e', 'eia', 'ela', 'elas', 'ele', 'eles', 'em', 'embora', 'enquanto', 'entre', 'essa', 'essas', 'esse', 'esses', 'esta', 'este', 'estes', 'estou', 'eu', 'hem', 'hum', 'ih', 'isso', 'isto', 'lhe', 'lhes', 'logo', 'mais', 'mas', 'me', 'menos', 'mesma', 'mesmas', 'mesmo', 'mesmos', 'meu', 'meus', 'mim', 'minha', 'minhas', 'muita', 'muitas', 'muito', 'muitos', 'na', 'nada', 'naquela', 'naquelas', 'naquele', 'naqueles', 'naquilo', 'nas', 'nela', 'nelas', 'nele', 'neles', 'nem', 'nenhum', 'nenhuma', 'nenhumas', 'nenhuns', 'nessa', 'nessas', 'nesse', 'nesses', 'nesta', 'nestas', 'neste', 'nestes', 'ninguém', 'nisso', 'nisto', 'no', 'nos', 'nossa', 'nossas', 'nosso', 'nossos', 'nós', 'o', 'oba', 'oh', 'olá', 'onde', 'opa', 'ora', 'os', 'ou', 'outra', 'outras', 'outrem', 'outro', 'outros', 'para', 'per', 'perante', 'pois', 'por', 'porque', 'portanto', 'porém', 'pouca', 'poucas', 'pouco', 'poucos', 'próprios', 'psit', 'psiu', 'quais', 'quaisquer', 'qual', 'qualquer', 'quando', 'quanta', 'quantas', 'quanto', 'quantos', 'que', 'quem', 'se', 'sem', 'seu', 'seus', 'si', 'sob', 'sobre', 'sua', 'suas', 'talvez', 'tanta', 'tantas', 'tanto', 'tantos', 'te', 'teu', 'teus', 'ti', 'toda', 'todas', 'todo', 'todos', 'trás', 'tu', 'tua', 'tuas', 'tudo', 'uh', 'ui', 'um', 'uma', 'umas', 'uns', 'ué', 'você', 'vossa', 'vossas', 'vosso', 'vossos', 'vária', 'várias', 'vário', 'vários', 'vós', 'à', 'ó', 'ô'],
  },
}

export default languages
